### ISSUE TITLE
Conflicting module name

### ISSUE THREAD

**Issue by biplap-sarkar** [wepay/signer-ruby#3]
After I include the signer using require 'signer'
I get the error "WePay is not a module".
My guess is this is due to conflict of definition of 'WePay'. It is defined as a class in our API SDK
and as a module in our signer SDK. Using any other module name works fine in my own signer repository.

**Comment by skyzyx** [comment]
\*sigh*

We should fix the Ruby "SDK" to be namespaced properly.

https://github.com/wepay/Ruby-SDK/blob/master/lib/wepay.rb

**Comment by biplap-sarkar** [comment]
Fixed after Ruby SDK namespace fix.
